### ISSUE TITLE
Linux Python 3.6 builds not present

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/yt-feedstock#16]
It looks like the Linux Python 3.6 builds haven't been uploaded. Any ideas what this could be due to? (looks like CircleCi ran without error but can't see the part in the log where the files get uploaded)

**Comment by jakirkham** [comment]
No clue. The log I downloaded from CircleCI from the most recent build is incomplete. However, it passes. We can try restarting.

However most times with upload issues it has been a product of some testing step going awry, which we have had to add guards around on Linux.

My suspicion is that the proposal put together in PR ( https://github.com/conda-forge/conda-smithy/pull/337 ) will be the real fix for issues like these.

**Comment by jakirkham** [comment]
FYI have gone ahead and restarted CircleCI.

**Comment by jakirkham** [comment]
No luck. I would think it is running into the build time limit, but it has only run ~30mins. I believe the time limit is ~2hrs. Any ideas as to why this is not working, @ngoldbaum ?

**Comment by ngoldbaum** [comment]
I have no idea why it's not working. It looks like the build output is truncated at 4 MB, so I can't see what ends up killing the build (if anything - it looks like the build is passing?) Perhaps we should be suppressing some of the voluminous output from the build process so we can see the full build log?

**Comment by jakirkham** [comment]
Good catch. Cutting down the output sounds like a good option. Would that be easy to do?

**Comment by ngoldbaum** [comment]
I have no idea, you likely have more experience with how conda-forge interacts with circleCI than I do. Somehow we need to suppress the compilation output generated by `conda-build`.

**Comment by Xarthisius** [comment]
We could pass `-q` to `setup.py install`. Also if it's fairly decent *gcc* `CFLAGS="-Wno-cpp"` would help a lot.

**Comment by Xarthisius** [comment]
I managed to trim out the output. 3.6 is simply not built. Only 2.7, 3.4 and 3.5 are present. What governs python versions in CircleCI builds?

**Comment by Xarthisius** [comment]
```
xarth@shakuras ~/codes/yt-feedstock (silence) $ grep -r CONDA_PY ci_support/run_docker_build.sh 
    export CONDA_PY=27
    export CONDA_PY=27
    export CONDA_PY=34
    export CONDA_PY=34
    export CONDA_PY=35
    export CONDA_PY=35
```
mystery solved?

**Comment by ngoldbaum** [comment]
Hmm, maybe that's a conda-smithy bug. It looks like when @astrofrog rerendered the feedstock it didn't update the circleci metadata: https://github.com/conda-forge/yt-feedstock/pull/15/files

**Comment by ngoldbaum** [comment]
@jakirkham should we just add the py3 metadata manually? Should this get reported as an issue against conda-smithy?

**Comment by jakirkham** [comment]
Thanks @Xarthisius . I should have looked at the CI files.

As for why it failed to add Python 3.6 for Linux, it could be that some dependency did not have Python 3.6 packages. `conda-smithy` will fail silently in that case. Should it? Probably not. Hence we have issue ( https://github.com/conda-forge/conda-smithy/issues/411 ). In the interim, we have to go back and check that are dependencies are satisfied on Python 3.6.

**Comment by astrofrog** [comment]
@jakirkham - I think it must be sympy, so I've opened a PR there:

https://github.com/conda-forge/sympy-feedstock/pull/5

However there too CircleCI wasn't updated *and* all dependencies do seem to exist for 3.6. Any ideas about what is going on there?

**Comment by jakirkham** [comment]
Actually now that I'm looking at `yt`, I think `pyembree` might be an issue. It is a Linux only dependency that doesn't seem to have Python 3.6 support. Plus it doesn't seem to exist in `defaults`.
