### ISSUE TITLE
Issue with rerendering

### ISSUE THREAD

**Issue by ngoldbaum** [conda-forge/yt-feedstock#9]
For some reason the last time we re-rendered this feedstock we had issues getting the output to come out correctly. See e.g. https://github.com/conda-forge/yt-feedstock/pull/8#discussion_r82230146

The solution was to comment out pyembree from the recipe and rerender, then add pyembree back in.

**Comment by jakirkham** [comment]
Please see this upstream issue ( https://github.com/conda-forge/conda-smithy/issues/387 ). I strongly suspect that PR ( https://github.com/conda-forge/conda-smithy/pull/401 ) will fix this for you. It explicitly sets the channels to use for re-rendering. So should be invariant of things like `.condarc` settings.

**Comment by ngoldbaum** [comment]
Closing this since I think we dealt with this a while ago.
